### ISSUE TITLE
Imgur bug

### ISSUE THREAD

**Issue by pmdevita** [pmdevita/vredditshare#4]
```
Decided to upload to <class 'core.hosts.imgur.ImgurHost'> <core.hosts.GifFile object at 0x7f4
26a430f28>
getting imgur album id... ropLwxf
uploading... wat
{'data': {'error': {'code': 1003,
                    'exception': {},
                    'message': '[ropLwxf]: File type invalid (1)',
                    'type': 'Exception_UploadError'},
          'method': 'POST',
          'request': '/upload'},
 'status': 415,
 'success': False}
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    result = process_comment(reddit, reddit.comment(message.id), q)
  File "/home/pmdevita/bots/vredditshare/core/process.py", line 148, in process_comment
    reversed_gif_file.audio)
  File "/home/pmdevita/bots/vredditshare/core/hosts/imgur.py", line 358, in upload
    id = imgurupload(file, gif_type, nsfw=nsfw)
  File "/home/pmdevita/bots/vredditshare/core/hosts/imgur.py", line 164, in imgurupload
    print("received wait ticket:", upload['data']['ticket'])
```

**Comment by pmdevita** [comment]
Imgur API has been completely redone, bug likely no longer exists.
